### DISCUSSION TITLE
k8s conf problem

### DISCUSSION THREAD

**Discussion by jonatanhost** [johanmeijer/grott#153] [Q&A] [answered]
I am trying to run grottserver on my kubernetes cluster but I can not get it to work. Anyone else that has done this and succeeded?

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grottserver
  namespace: home
spec:
  selector:
    matchLabels:
      app: grottserver
  replicas: 1
  template:
    metadata:
      labels:
        app: grottserver
    spec:
      containers:
      - name: grottserver
        image: ledidobe/grottserverrpi:2.7.4
        env:
        - name: TZ
          value: "Europe/Stockholm"
        - name: gmqttip
          value: 192.168.0.199
        - name: ggrottip
          value: 192.168.0.205
        ports:
        - containerPort: 5279
__________
kind: Service
apiVersion: v1
metadata:
  name: grottserver
  namespace: home
  annotations:
    metallb.universe.tf/allow-shared-ip: 'true'
spec:
  ports:
    - name: '5279'
      protocol: TCP
      port: 5279
      targetPort: 5279
    - name: '5782'
      protocol: TCP
      port: 5782
      targetPort: 5782
  selector: 
    name: grottserver
  type: LoadBalancer
  loadBalancerIP: 192.168.0.205

**Comment by johanmeijer** [comment]
@jonatanhost: I see nobody answered this one yet. Do you already found a solution. I am not running Kubernetics at home (docker swarm / portainer will work for that). 

But have to look at it for work. Maybe I can do somethings at home then also.  But I have to start form scratch so will not be able to help you very quickly.

**Comment by rvandermost** [comment, marked as answer]
@jonatanhost I looked at your config but cannot find any flaws. This is the config I'm using on K8s. Please note that the service gets exposed on port `30100`.

EDIT: looking at your config again.. You might want to make sure your selectors and labels are right. The labels on the POD should be the same as you selector in the Service. You use the `app` label in the POD and `name` selector in the Service.

Namespace:
```apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: grott-p
spec: {}
status: {}
```

deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grott
  name: grott
  namespace: grott-p
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grott
  strategy: {}
  template:
    metadata:
      labels:
        app: grott
    spec:
      containers:
      - image: ledidobe/grott:latest
        name: grott
        ports:
        - containerPort: 5279
        livenessProbe:
          tcpSocket:
            port: 5279
          initialDelaySeconds: 10
        readinessProbe:
          tcpSocket:
            port: 5279
          initialDelaySeconds: 10
        env:
          - name: gblockcmd
            value: "True"
          - name: gpvoutput
            value: "False"
          - name: gmqttip
            value: 10.43.0.93
          - name: ginvtype
            value: "tl3"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
```

NodePort:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grott
  name: grott
  namespace: grott-p
spec:
  ports:
  - name: 5279-5279
    port: 5279
    targetPort: 5279
    nodePort: 30100
  selector:
    app: grott
  type: NodePort
```

[clusterip.yaml.txt](https://github.com/johanmeijer/grott/files/9439516/clusterip.yaml.txt)
[deployment.yaml.txt](https://github.com/johanmeijer/grott/files/9439517/deployment.yaml.txt)
[ns.yaml.txt](https://github.com/johanmeijer/grott/files/9439518/ns.yaml.txt)
