### DISCUSSION TITLE
Energy Spikes

### DISCUSSION THREAD

**Discussion by jupppo** [johanmeijer/grott#244] [Q&A] [answered]
Hi everyone,

I am getting sometimes (1-2 times a week) an enormes energy spike in the data. First I thought is is a home assistant problem, but then I catched it in the mqtt stream. 
Here is what I get:

['elocalload_tot'] | 429.496.730,3 kWh |  
-- | -- | --
Solar Total  | 429.496.730,3 kWh |   
Battery Discharged | 429.496.729,7 kWh |  
Battery Charged | -429.496.730 kWh

Any idea how to prevent this or where its coming from?

**Comment by johanmeijer** [comment]
Can you retrieve the Grott log information with this failure? 

Which version of Grott do you use? The latest version has some code to prevent from processing invalid records.

**Reply by jupppo** [reply]
Hey Johan,

thanks for the quick reply. Where do I find the logs? I used the lastest version from the beta.

Best
Thomas

**Comment by johanmeijer** [comment]
How do you use grott (docker, stand alone)?

**Reply by jupppo** [reply]
I use stand alone on Debian 11

**Comment by jupppo** [comment]
It looked like it was a firewall  problem, when too many messages got out.

**Comment by johanmeijer** [comment]
/Ok. Are you able to prevent this? Can this being solved

**Comment by jupppo** [comment]
so far it looks good. Since 1 week no spike

**Comment by jupppo** [comment]
After two weeks my spikes are back :-)

**Reply by jupppo** [reply]
I got another data spike yesterday. Here is the data from journald:


Dez 22 19:18:15 grott grott[20337]:          - Growatt new layout processing
Dez 22 19:18:15 grott grott[20337]:                  - decrypt       :  True
Dez 22 19:18:15 grott grott[20337]:                  - offset        :  6
Dez 22 19:18:15 grott grott[20337]:                  - record layout :  T06NNNNXSPH
Dez 22 19:18:15 grott grott[20337]:          - Grott data record date/time processing started
Dez 22 19:18:15 grott grott[20337]:          - date-time:  2022-12-22T19:17:14
Dez 22 19:18:15 grott grott[20337]:          - Grott values retrieved:
Dez 22 19:18:15 grott grott[20337]:                  -  datalogserial        :  JPC6A296K7
Dez 22 19:18:15 grott grott[20337]:                  -  pvserial             :  OMCUCDV020
Dez 22 19:18:15 grott grott[20337]:                  -  pvstatus             :  6
Dez 22 19:18:15 grott grott[20337]:                  -  pvpowerin            :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  pv1voltage           :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  pv1current           :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  pv1watt              :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  pv2voltage           :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  pv2current           :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  pv2watt              :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  pvpowerout           :  -0.1
Dez 22 19:18:15 grott grott[20337]:                  -  pvfrequentie         :  655.4
Dez 22 19:18:15 grott grott[20337]:                  -  pvgridvoltage        :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  pvgridcurrent        :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  pvgridpower          :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  pvgridvoltage2       :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  pvgridcurrent2       :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  pvgridpower2         :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  pvgridvoltage3       :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  pvgridcurrent3       :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  pvgridpower3         :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  totworktime          :  596523.2
Dez 22 19:18:15 grott grott[20337]:                  -  eactoday             :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  pvenergytoday        :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  eactotal             :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  epvtotal             :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  epv1today            :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  epv1total            :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  epv2today            :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  epv2total            :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  pvtemperature        :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  pvipmtemperature     :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  pvboosttemp          :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  bat_dsp              :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  eacharge_today       :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  eacharge_total       :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  batterytype          :  65535
Dez 22 19:18:15 grott grott[20337]:                  -  uwsysworkmode        :  65535
Dez 22 19:18:15 grott grott[20337]:                  -  systemfaultword0     :  65535
Dez 22 19:18:15 grott grott[20337]:                  -  systemfaultword1     :  65535
Dez 22 19:18:15 grott grott[20337]:                  -  systemfaultword2     :  65535
Dez 22 19:18:15 grott grott[20337]:                  -  systemfaultword3     :  65535
Dez 22 19:18:15 grott grott[20337]:                  -  systemfaultword4     :  65535
Dez 22 19:18:15 grott grott[20337]:                  -  systemfaultword5     :  65535
Dez 22 19:18:15 grott grott[20337]:                  -  systemfaultword6     :  65535
Dez 22 19:18:15 grott grott[20337]:                  -  systemfaultword7     :  65535
Dez 22 19:18:15 grott grott[20337]:                  -  pdischarge1          :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  p1charge1            :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  vbat                 :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  SOC                  :  655.4
Dez 22 19:18:15 grott grott[20337]:                  -  pactouserr           :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  pactousertot         :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  pactogridr           :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  pactogridtot         :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  plocaloadr           :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  plocaloadtot         :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  spdspstatus          :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  spbusvolt            :  6553.5
Dez 22 19:18:15 grott grott[20337]:                  -  etouser_tod          :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  etouser_tot          :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  etogrid_tod          :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  etogrid_tot          :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  edischarge1_tod      :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  edischarge1_tot      :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  eharge1_tod          :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  eharge1_tot          :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  elocalload_tod       :  429496729.5
Dez 22 19:18:15 grott grott[20337]:                  -  elocalload_tot       :  429496729.5

**Comment by johanmeijer** [comment]
Hmm not oke. Maybe we can try to build in some kind of filter in Grott. Let me think about it.

**Comment by johanmeijer** [comment]
Kan you send the hex growatt original data from the log? pvstatus = 6 is not what I expect for a SPH (I think).

**Reply by jupppo** [reply]
Merry Christmas Johann,
Unfortunatly I dont have the Hex Part anymore. I Just keep a few days of log. next time I save the whole Part. 
PV Status 6 ist Battery Operation Mode in the SPH.

Best

**Comment by gaoxuannuli** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，您发的邮件我已收到，我会尽快给您回复。祝好！

**Comment by jupppo** [comment, marked as answer]
I finally solved the energy spike issue by filtering the mqtt message in the home assistant.
This should be accordingly applied to the templates for homeassistant for each used entity. As soon as I have some time, I will update these.

```
mqtt:
  sensor:
    - state_topic: energy/growatt
      value_template: "{{ value_json['values']['epvtotal'] | int(0) / 10 }}" 
      availability_template: "{{ value_json['values']['epvtotal'] | int(0) < 200000}}"
      availability_topic: energy/growatt
      payload_available: true
      payload_not_available: false        
      unique_id: growatt_generated_energy_total
      device_class: energy
      unit_of_measurement: "kWh"
      state_class: "total_increasing" 
      name: Growatt - Generated energy (Total)
      icon: mdi:solar-power
```

Important are these filters, they mark the payload as unavailable and it wont get recorded:

    availability_template: "{{ value_json['values']['epvtotal'] | int(0) < 200000}}"
    availability_topic: energy/growatt
    payload_available: true
    payload_not_available: false

**Comment by jupppo** [comment]
Here is the sensors_grott.yaml file for home assistant. Can be either included in configuration.yaml or sensors.yaml (if used). It includes the sensors for grott, plus some customs calculation (like solar usage % per day).

The filter solution is tested from me and works perfectly from me. 
@johanmeijer :Feel free to attach the file to the examples, if you like.

Best

[sensors_grott.yaml.txt](https://github.com/johanmeijer/grott/files/10380654/sensors_grott.yaml.txt)

**Reply by HaareistNase** [reply]
Thanks for this file.
As a complete Home-Assistant-Newbie it helps me a lot to get Sensordata from MQTT. I struggle for hours to figure out how to do it. (After I figure out how git works on raspi, how I get python installed on the pi, and that mosquitto has to be installed and configured tooo, that this functionallity is not from grott^^).

BUT ... Since HASS changed the Sensor-Format in YAMEL a short time ago, you have to rewrite the whole list.

I have done this today (I can provide the list, if needed), with alle the MQTT-Sensors, but I did not find out how the first part of the file translate to the new format.
Maybe you can help me out (again^^).

This part is not working anymore, and I do not get it done :-)

```
sensor:
#Grott Parameters
      growatt_inverter:
        unique_id: growatt_invertertype
        friendly_name: Growatt - Type
        # Please set the type of your inverter
        value_template: "XXX"
        icon_template: mdi:select-inverse
      growatt_datalogger_type:
        unique_id: growatt_datloggertype
        friendly_name: Growatt - Datalogger type
        # Please set the type of your datalogger
        value_template: "XXX"
        icon_template: mdi:select-inverse
      growatt_datalogger_serial:
        unique_id: growatt_datlogger_serial
        friendly_name: Growatt - Datalogger serienr
        # Please set the serial number of your datalogger
        value_template: "XXX"
        icon_template: mdi:select-inverse

#Growatt (grott) Custom Measurements
  - sensor:
      - name: "Growatt - Netto Energiebezug"
        unit_of_measurement: "W"
        unique_id: netto_energie_actual
        device_class: power
        state_class: "measurement"         
        state: >
          {% set fromgrid = states('sensor.growatt_energy_from_grid_actual_2') | float %}
          {% set togrid = states('sensor.growatt_energy_to_grid_actual') | float %}
          {{ (fromgrid - togrid) | round(1, default=0) }}
          
  - sensor:
      - name: "Growatt - PV Energy Calculated Today"
        unit_of_measurement: "kWh"
        unique_id: netto_energie_calc_today
        device_class: energy
        state_class: "measurement" 
        state: >
          {% set ETstr1 = states('sensor.growatt_total_enegry_usage_actual_3') | float %}
          {% set ETstr2 = states('sensor.growatt_total_enegry_usage_actual_5') | float %}
          {{ (ETstr1 + ETstr2) | round(1, default=0) }} 

  - sensor:
      - name: "Growatt - PV Energy Calculated Total (Actual)"
        unit_of_measurement: "W"
        unique_id: netto_energie_calc_actual
        device_class: power
        state_class: "measurement" 
        state: >
          {% set EAstr1 = states('sensor.growatt_string_1_watt') | float %}
          {% set EAstr2 = states('sensor.growatt_string_2_watt') | float %}
          {{ (EAstr1 + EAstr2) | round(1, default=0) }}                

  - sensor:
      - name: "Growatt - Batterieladeleistung"
        unit_of_measurement: "kW"
        unique_id: battnetto
        device_class: energy
        state_class: "measurement" 
        state: >
          {% set BatTo = states('sensor.growatt_energy_to_battery_actual') | float %}
          {% set BatFrom= states('sensor.growatt_energy_from_battery_actual') | float %}
          {{ (BatTo - BatFrom) | round(1, default=0) }}      

  - sensor:
      - name: "Eigenproduktion"
        unit_of_measurement: "%"
        state_class: "measurement" 
        unique_id: "223456789987654321"
        state: >
          {% set lgrid = states('sensor.growatt_total_enegry_load_today') | float %}
          {% set sepv = states('sensor.growatt_energy_from_grid_today_2') | float %}        
          {{ ((lgrid - sepv) * 100 / lgrid) | round(2, default=0) }} 
  - sensor:
      - name: "Total Solar Percent"
        unit_of_measurement: "%"
        state_class: "measurement" 
        unique_id: "233456789987654321"
        state: >
          {% set ltgrid = states('sensor.growatt_lifetime_load_consumption_3') | float %}
          {% set ltsepv = states('sensor.growatt_generated_energy_total') | float %}        
          {{ ((ltsepv * 100) / ltgrid ) | round(2, default=0) }} 
         
  - sensor:
      - name: "battery_effectiveness"
        unit_of_measurement: "%"
        state_class: "measurement" 
        unique_id: "993456789987654321"
        state: >
          {% set batin = states('sensor.growatt_battery_charged_total') | float %}
          {% set batout = states('sensor.growatt_battery_discharged_total') | float %}
          {{ (batout * 100 / batin) | round(2, default=0) }}  
```
