### DISCUSSION TITLE
Disable or limit inverter feed to grid

### DISCUSSION THREAD

**Discussion by anoppe** [johanmeijer/grott#529] [Q&A]
With the utility providers trying to oppose more and more measures to let the PV-panel owners pay for feeding produced energy to the grid, I was wondering if it is possible to use Grott to configure the inverter to limit feed or stop completely.
It would be nice if I could configure automation in HASS which instructs Grott to limit feed or turn off the inverter.

**Comment by ebbz** [comment]
I found out it is possible to disable the inverter by using grottserver. You will find some info in this [thread](https://github.com/johanmeijer/grott/discussions/98)

After setting up grott and grottserver. You are able to send register commands to your inverter. My inverter, and I think most of the inverters out there, user register 3 to set an export limit. You can set this to any value between 0 and 100 to limit your export percentage.

I have made some rest_commands calling grottserver in home assistant to start and stop exporting via automations based on the energy price.

**Reply by gijs007** [reply]
> You can set this to any value between 0 and 100 to limit your export percentage.

This is pretty cool, I tried experimenting with it. But the inverter shows 401 error code and is flashing red. Even after disabling the export limit, although the inverter is working normally again.

Do we need some extra devices, to limit the export? As shown in this video: https://www.youtube.com/watch?v=bKH7i0Wyx94&t=145s

> I have made some rest_commands calling grottserver in home assistant to start and stop exporting via automations based on the energy price.

Could you share the rest_commands used to start/stop/limit?

**Reply by anoppe** [reply]
I've got a MIN 2500TL-X and I'm struggling to find the correct registers that reflect the export limit toggle and the register to set the actual limit. I haven't been able to find this in the thread you mentioned either @ebbz , but maybe I've overlooked it. I've also scanned this document, but I'm a bit puzzled which register to use. https://www.photovoltaicsolar.in/Growatt_Manual/MAX%20Series%20Modbus%20RTU%20Protocol.pdf

Do you have any idea?

**Reply by anoppe** [reply]
Writing reg 3 doesn't work :(
```
%  curl -XPUT 'http://192.168.178.9:5782/inverter?command=register&register=03&value=50&inverter=*****'
no or invalid response received%    
```

**Reply by anoppe** [reply]
I've enabled the export limit using the official Growatt UI, and then I was able to change these registers (3 and 4). However, as soon as I enabled the export limit, the inverter stopped exporting completely, despite setting the value to 0, or 100. Tried both, to be sure...

**Reply by PedroKTFC** [reply]
This is what I use for my [registers list](https://github.com/johanmeijer/grott/blob/Beta-(2.8.x)/documentatie/registers.md). Seems pretty accurate in my experience.

**Reply by anoppe** [reply]
thanks @PedroKTFC .
I see that the MIN types don't have their registers specified yet. 
Any Idea what 03 and 04 register range should mean:
> TL-X/TL-XH/TL-XH US (MIN Type):
03 register range: 0-124, 3000-3124, 3125-3249 (TL-XHUS)
04 register range: 3000-3124, 3125-3249, 3250-3374 (TL-XH)

**Reply by ebbz** [reply]
Add this to to your configuration.yaml in home assitant

```
rest_command:
  turn_off_solar:
    url: "http://{ipgrowattserver}:5782/inverter?inverter={inverterid}&command=register&register=03&value=0"
    method: put
  turn_on_solar:
    url: "http://{ipgrowattserver}:5782/inverter?inverter={inverterid}&command=register&register=03&value=100"
    method: put
```

The automation i am using to turn off the inverter:
```
alias: DisableInverter
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.electricity_price_xxx
action:
  - if:
      - alias: If negative energy price
        condition: numeric_state
        entity_id: sensor.electricity_price_xxx
        below: 0
    then:
      - alias: Disable inverter
        service: rest_command.turn_off_solar
        data: {}
    else:
      - alias: Enable inverter
        service: rest_command.turn_on_solar
        data: {}
mode: single
```
