### DISCUSSION TITLE
ShineMaster external load meter

### DISCUSSION THREAD

**Discussion by ealfaroc** [johanmeijer/grott#625] [Q&A] [answered]
I have a photovoltaic installation with two 6000TL-XH inverters connected to the rs485_1 channel and a DDSU666 CHINT meter connected to the rs485_2 channel of the ShineMaster.
I could somehow read the measurements of the CHINT DDSU666 meter?

With grott proxy I only see the messages from the photovoltaic inverters.

![ShineMaster](https://github.com/user-attachments/assets/d7c1559c-bbca-4ab5-9b80-19fb64c7ced2)

**Comment by johanmeijer** [comment]
I think it should be possible. I need some grott log information. Do you see any messages with reference to t06nn1b or t06nn20  ( nn is a number in your case probably 03).

**Reply by ealfaroc** [reply]
I found these messages in the log:

^[[36mgrott                |^[[0m        - Growatt original Data:
^[[36mgrott                |^[[0m                \x00\x01\x00\x06\x00\x60\x23\x1b\x03\x2b\x2b\x47\x22\x3e\x31\x77\x46\x5e\x77
^[[36mgrott                |^[[0m                \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
^[[36mgrott                |^[[0m                \x6f\x31\x78\x75\x60\x52\x5e\x72\x77\x57\x46\x47\x73\x5c\x5e\x5b\x52\x5a\x44
^[[36mgrott                |^[[0m                \x6b\x44\x57\x47\x4f\x46\x58\x6a\x43\x57\x46\x4f\x41\x58\x70\x42\x5c\x59\x53
^[[36mgrott                |^[[0m                \x58\x44\x69\x4b\x43\x5b\x54\x44\x5a\x77\x5e\x43\x45\x53\x40\x47\x69\x41\x43
^[[36mgrott                |^[[0m                \x45\x55\x43\x4d\x69\x47\x43\xaa\x1e
^[[36mgrott                |^[[0m        - Grott automatic protocol detection
^[[36mgrott                |^[[0m        - Grott data record length 104
^[[36mgrott                |^[[0m        - layout   :  T06231b
^[[36mgrott                |^[[0m        - no matching record layout found, try generic
^[[36mgrott                |^[[0m        - Record layout used :  T06231b
^[[36mgrott                |^[[0m        - Growatt data decrypted V2
^[[36mgrott                |^[[0m        - Grott Growatt data decrypted
^[[36mgrott                |^[[0m        - Growatt plain data:
^[[36mgrott                |^[[0m                000100060060231b44594430434a4530343100000000000000000000000000000000000000000
^[[36mgrott                |^[[0m                046190114152c1d00363233342e312c332e302c3638302e322c2d3138312e352c3730332e322c
^[[36mgrott                |^[[0m                302e392c2c35302e302c2c323234332e332c323437392e352cdd7f
^[[36mgrott                |^[[0m        - Grott data ack record or data record not defined no processing done


^[[36mgrott                |^[[0m        - Growatt original Data:
^[[36mgrott                |^[[0m                \x00\x01\x00\x06\x00\x63\x23\x1b\x03\x2b\x2b\x47\x22\x3e\x31\x77\x46\x5e\x77
^[[36mgrott                |^[[0m                \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
^[[36mgrott                |^[[0m                \x6f\x31\x78\x75\x60\x52\x43\x75\x77\x58\x46\x46\x72\x5c\x59\x5b\x50\x47\x5a
^[[36mgrott                |^[[0m                \x77\x5e\x5d\x4e\x51\x4d\x5a\x74\x5e\x42\x46\x56\x45\x5a\x76\x5e\x5d\x4e\x55
^[[36mgrott                |^[[0m                \x46\x5a\x74\x5e\x5f\x59\x58\x58\x58\x72\x42\x41\x47\x4d\x58\x46\x75\x46\x5c
^[[36mgrott                |^[[0m                \x59\x57\x58\x46\x73\x45\x56\x59\x54\x58\xcb\x30
^[[36mgrott                |^[[0m        - Grott automatic protocol detection
^[[36mgrott                |^[[0m        - Grott data record length 107
^[[36mgrott                |^[[0m        - layout   :  T06231b
^[[36mgrott                |^[[0m        - no matching record layout found, try generic
^[[36mgrott                |^[[0m        - Record layout used :  T06231b
^[[36mgrott                |^[[0m        - Growatt data decrypted V2
^[[36mgrott                |^[[0m        - Grott Growatt data decrypted
^[[36mgrott                |^[[0m        - Growatt plain data:
^[[36mgrott                |^[[0m                000100060063231b44594430434a4530343100000000000000000000000000000000000000000
^[[36mgrott                |^[[0m                04619011415311a00393232352e362c31332e302c323930392e332c2d3137312e312c32393432
^[[36mgrott                |^[[0m                2e332c302e392c2c35302e302c2c323234332e362c323437392e352cbf77
^[[36mgrott                |^[[0m        - Grott data ack record or data record not defined no processing done


^[[36mgrott                |^[[0m        - Growatt original Data:
^[[36mgrott                |^[[0m                \x00\x01\x00\x06\x00\x63\x23\x1b\x03\x2b\x2b\x47\x22\x3e\x31\x77\x46\x5e\x77
^[[36mgrott                |^[[0m                \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
^[[36mgrott                |^[[0m                \x6f\x31\x78\x75\x60\x52\x44\x78\x77\x58\x46\x46\x71\x5c\x5f\x5b\x50\x46\x5a
^[[36mgrott                |^[[0m                \x7f\x5e\x5d\x4f\x59\x4c\x5a\x72\x5e\x42\x46\x57\x46\x5a\x7f\x5e\x5d\x4e\x51
^[[36mgrott                |^[[0m                \x44\x5a\x76\x5e\x5f\x59\x58\x58\x58\x72\x42\x41\x47\x4d\x58\x46\x75\x46\x5c
^[[36mgrott                |^[[0m                \x59\x59\x58\x46\x73\x45\x56\x59\x54\x58\xc6\xce
^[[36mgrott                |^[[0m        - Grott automatic protocol detection
^[[36mgrott                |^[[0m        - Grott data record length 107
^[[36mgrott                |^[[0m        - layout   :  T06231b
^[[36mgrott                |^[[0m        - no matching record layout found, try generic
^[[36mgrott                |^[[0m        - Record layout used :  T06231b
^[[36mgrott                |^[[0m        - Growatt data decrypted V2
^[[36mgrott                |^[[0m        - Grott Growatt data decrypted
^[[36mgrott                |^[[0m        - Growatt plain data:
^[[36mgrott                |^[[0m                000100060063231b44594430434a4530343100000000000000000000000000000000000000000
^[[36mgrott                |^[[0m                04619011415361700393232362e302c31322e382c323838382e352c2d3136322e382c32393030
^[[36mgrott                |^[[0m                2e312c302e392c2c35302e302c2c323234332e382c323437392e352cb289
^[[36mgrott                |^[[0m        - Grott data ack record or data record not defined no processing done

**Reply by ealfaroc** [reply]
I think the data structure is the following:

000100060065231b44594430434a45303431000000000000000000000000000000000000000000461901160d0627003b3233322e312c33302e352c2d373039302e362c2d3135382e302c373038382e302c2d302e392c2c34392e392c2c323332302e302c323530352e342c0050

e#DYD0CJE041F';232.1,30.5,-7090.6,-158.0,7088.0,-0.9,,49.9,,2320.0,2505.4,P
								   
Voltage single precision floating decimal 2 R 
I Current single precision floating decimal 2 R 
P Conjunction active power，the unit is KW single precision floating decimal 2 R 
Q Conjunction reactive power，the unit is Kvar single precision floating decimal 2 R 
RESERVED RESERVED single precision floating decimal 2 R 
PF Conjunction power factor single precision floating decimal 2 R 
RESERVED RESERVED single precision floating decimal 2 R 
Freq Frequency single precision floating decimal 2 R 
RESERVED RESERVED single precision floating decimal 2 R Electrical data of the secondary side 
Ep Active in electricity single precision floating decimal 2 R 
-Ep Reverse in electricity  single precision floating decimal 2 R

**Reply by ealfaroc** [reply]
Would this new layout be correct?

self.recorddict15 = {"T06231b": {
    "decrypt"  : {"value" :"True"},
    "datalogserial"  : {"value" :16, "length" : 10, "type" : "text","incl" : "yes"},
    "device"  : {"value": "DDSU666 ","type" : "def","incl" : "no"}, 
    'voltage'  : {'pos': 0, 'type': 'float'},    # Voltage
    'current'  : {'pos': 1, 'type': 'float'},    # Current
    'active_power'  : {'pos': 2, 'type': 'float'}, # Active power (P)
    'reactive_power'  : {'pos': 3, 'type': 'float'}, # Reactive power (Q)
    'reserved1'  : {'pos': 4, 'type': 'float'},  # RESERVED
    'power_factor'  : {'pos': 5, 'type': 'float'}, # Power factor (PF)
    'reserved2'  : {'pos': 6, 'type': 'float'},  # RESERVED
    'frequency'  : {'pos': 7, 'type': 'float'},  # Frequency
    'reserved3'  : {'pos': 8, 'type': 'float'},  # RESERVED
    'active_electricity'  : {'pos': 9, 'type': 'float'}, # Active electricity (Ep)
    'reverse_electricity'  : {'pos': 10, 'type': 'float'} # Reverse electricity (-Ep)
}

**Comment by johanmeijer** [comment, marked as answer]
Ok. This is total new record layout. Also different then other chint meter I have seen (see also #186). 

With the above information I created and tested a new json layout file for you (see attached file T06231b.json. If you download this file and put it in the grott directory (stop start grott) it should work. 

I think you are the only one who can validate if the values are ok (compare the grott values with the growatt server/app values). 

Your reserved 1 also gives a value. I am not sure what that can be. 

The values from your record: 

![image](https://github.com/user-attachments/assets/bc8ca72f-b13c-4ac8-9e8e-33948c816d9f)
[T06231b.json](https://github.com/user-attachments/files/18526663/T06231b.json)

**Reply by ealfaroc** [reply]
It works perfectly, thank you very much.

grott                |   - Grott Growatt data decrypted
grott                |   - Growatt plain data:
grott                |           000100060065231b44594430434a4530343100000000000000000000000000000000000000000
grott                |           0461901180b2817003b3235302e352c33302e312c2d373534322e332c2d3138362e312c373534
grott                |           372e322c2d302e392c2c35302e302c2c323337392e332c323534342e342ccec0
grott                |   - Growatt new layout processing
grott                |           - decrypt       :  True
grott                |           - offset        :  6
grott                |           - record layout :  T06231b
grott                |
grott                |   - Grott data record date/time processing started
grott                |   - date-time:  2025-01-24T11:40:23
grott                |   - Grott values retrieved:
grott                |           -  datalogserial        :  DYD0CJE041
grott                |           -  voltage              :  250.5
grott                |           -  current              :  30.1
grott                |           -  active_power         :  -7542.3
grott                |           -  reactive_power       :  -186.1
grott                |           -  reserved1            :  7547.2
grott                |           -  power_factor         :  -0.9
grott                |           -  reserved2            :
grott                |           -  frequency            :  50.0
grott                |           -  reserved3            :
grott                |           -  active_electricity   :  2379.3
grott                |           -  reverse_electricity  :  2544.4
grott                |           -  device               :  DDSU666
grott                |   - MQTT jsonmsg:
grott                |                   {"device": "DDSU666", "time": "2025-01-24T11:40:23", "buffered": "no",
grott                |                   "values": {"datalogserial": "DYD0CJE041", "voltage": "250.5", "current":
grott                |                   "30.1", "active_power": "-7542.3", "reactive_power": "-186.1", "reserved1":
grott                |                   "7547.2", "power_factor": "-0.9", "reserved2": "", "frequency": "50.0",
grott                |                   "reserved3": "", "active_electricity": "2379.3", "reverse_electricity":
grott                |                   "2544.4", "device": "DDSU666"}}
grott                |   - Grott MQTT topic used : energy/growatt
grott                |   - MQTT message message sent

**Comment by ealfaroc** [comment]
Sensors for home assistan.

```
mqtt:
  sensor:
    - name: "DDSU666 Voltage"
      state_topic: "energy/growatt"
      value_template: "{{ value_json['values']['voltage'] if value_json.device == 'DDSU666' }}"
      unit_of_measurement: "V"
      state_class: measurement
      device_class: voltage

    - name: "DDSU666 Current"
      state_topic: "energy/growatt"
      value_template: "{{ value_json['values']['current'] if value_json.device == 'DDSU666' }}"
      unit_of_measurement: "A"
      state_class: measurement
      device_class: current

    - name: "DDSU666 Active Power"
      state_topic: "energy/growatt"
      value_template: "{{ value_json['values']['active_power'] if value_json.device == 'DDSU666' }}"
      unit_of_measurement: "W"
      state_class: measurement
      device_class: power

    - name: "DDSU666 Reactive Power"
      state_topic: "energy/growatt"
      value_template: "{{ value_json['values']['reactive_power'] if value_json.device == 'DDSU666' }}"
      unit_of_measurement: "VAR"
      state_class: measurement
      device_class: reactive_power

    - name: "DDSU666 Power Factor"
      state_topic: "energy/growatt"
      value_template: "{{ value_json['values']['power_factor'] if value_json.device == 'DDSU666' }}"
      state_class: measurement

    - name: "DDSU666 Frequency"
      state_topic: "energy/growatt"
      value_template: "{{ value_json['values']['frequency'] if value_json.device == 'DDSU666' }}"
      unit_of_measurement: "Hz"
      state_class: measurement
      device_class: frequency

    - name: "DDSU666 Active Electricity"
      state_topic: "energy/growatt"
      value_template: "{{ value_json['values']['active_electricity'] if value_json.device == 'DDSU666' }}"
      state_class: total
      unit_of_measurement: "kWh"
      device_class: energy

    - name: "DDSU666 Reverse Electricity"
      state_topic: "energy/growatt"
      value_template: "{{ value_json['values']['reverse_electricity'] if value_json.device == 'DDSU666' }}"
      unit_of_measurement: "kWh"
      state_class: total
      device_class: energy
```
