### ISSUE TITLE
Environment variable names needs to be lowercase

### ISSUE THREAD

**Issue by bkleef** [johanmeijer/grott#102]
In version 2.6.1g environment variable names must be lowercase otherwise the values will not be set in the application.

```
version: "3.4"
services:
  grott:
    container_name: grott
    image: ledidobe/grott:latest
    environment:
      - TZ=Europe/Amsterdam
      - gnomqtt=True
      - gpvoutput=False
      - ginflux=False
      - ginflux2=True
      - gifip=influxdb
      - gifport=8086
...
```

Environment variables are normally set uppercase (Docker). It took me a while to realize that this application expects them lowercase.

Can you minimally support uppercase?
