### ISSUE TITLE
Portainer Stacks Setup

### ISSUE THREAD

**Issue by mjdyson** [johanmeijer/grott#116]
Hello, I'm trying to re-setup Grott using Portainer - a docker manager GUI. It has a concept of Stacks, which work like Docker compose.

For whatever reason, I cannot seem to get the data into InfluxDB.

I wonder if anyone could point me towards an answer?

The Docker-Compose-like file I've been using attempts to include an image of grafana and influxDB. 

```
version: '3.3'
services:
    grott:
        network_mode: host
        image: ledidobe/grott
        container_name: grott
        restart: unless-stopped
        ports:
            - "5279:5279"
        environment:
            - ginvtype=sph
            - gblockcmd=true 
            - gnomqtt=false
            - gmqttip=192.168.30.30
            - gmqttauth=false
            - gmqttuser=homeassistant
            - gmqttpassword=MySecurePassword
            - gpvoutput=false
            - gpvapikey=yourapikey 
            - gpvinverterid1
            - gpvsystemid1=12345
            - ginflux=true
            - ginflux2=true
            - gifip=localhost
            - gifport=8086
            - giftoken=MyToken
            - giforg=grott_org
            - gifbucket=grott_bucket
            - gextension=false
            - gextname=grottext
            - 'gextvar={"ip":"192.168.30.109","port":"8000"}'
            - TZ=Europe/London
    grafana:
      image: grafana/grafana-oss
      container_name: grafana
      restart: always
      ports:
        - 3000:3000
    influxdb:
      image: influxdb
      container_name: influxdb
      restart: always
      ports:
        - 8086:8086
```
