### ISSUE TITLE
Idea: using custom DNS entry for ShineLan-X?

### ISSUE THREAD

**Issue by Lyve1981** [johanmeijer/grott#138]
Another idea I am having how to point a ShineLan-X USB module to grott would be to use a DNS override. Lets say that the ShineLan-X IP is 192.168.1.10 and grott is 192.168.1.15, a configuration for unbound 1.6 could look like this:

```
server:
  access-control-view: 192.168.1.10/32 grott
view:
  name: "grott"
  local-data: "server.growatt.com. 90 IN A 192.168.1.15"
  view-first: yes
```
What this does is to replace the IP address of server.growatt.com only for the ShineLan-X USB module. Other clients in the same net would still be able to access server.growatt.com in regular fashion.

However: Did anyone ever try if this works? It can only work if ShineLan-X does **not** check the validity for the DNS entry for server.growatt.com. My inverter is getting installed this week so right now I cannot test it. If no one else knows, I'll report back after installation. Maybe this is worth being added to the wiki if this works?
