### ISSUE TITLE
PVOutput Energy not reset at night

### ISSUE THREAD

**Issue by toaomatis** [johanmeijer/grott#182]
I have recently installed a new PV system with a **Growatt MOD 4000TL3-X** converter.

For two days it [went fine](https://www.pvoutput.org/list.jsp?id=79546&sid=93706), but this morning the PVOutput Energy is not reset to 0: https://www.pvoutput.org/intraday.jsp?id=79546&sid=93706&dt=20221003

I restarted the Docker container, but no success. I do see correct values in my Growatt dashboard: 
![20221003_102525_Selection_001](https://user-images.githubusercontent.com/545338/193532877-3144b139-1a7f-4975-9b9b-28482879cd6b.png)

My `docker-compose.yaml` looks like this:
```yaml
version: '3.3'
services:
    grott:
        image: ledidobe/grott
        container_name: grott
        restart: unless-stopped
        ports:
            - "5279:5279"
        environment:
            - ginvtype=tl3
            - gblockcmd=False 
            - gnomqtt=True
            - gmqttip=localhost
            - gmqttauth=False
            - gmqttuser=growatt
            - gmqttpassword=growatt2020
            - gpvoutput=True
            - gpvapikey=....
            - gpvinverters=1
            - gpvinverterid1=systemidX
            - gpvsystemid1=93706
            - ginflux=False
            - ginflux2=False
            - gifdbname=grottdb
            - gifip=localhost
            - gifport=8086
            - gifuser=grott
            - gigpassword=growatt2020
            - giftoken=influx_token
            - giforg=grottorg
            - gifbucket=grottdb
            - gextension=false
            - gextname=grottext
            - 'gextvar = {"ip": "192.168.0.47", "port": "8000"}'
            - TZ=Europe/Amsterdam 
```
