### ISSUE TITLE
Grott connection error: peer has disconnected

### ISSUE THREAD

**Issue by RedFoxy** [johanmeijer/grott#239]
Hi!
I've an inverter Growatt SPH3000 connected to a ShineLanBox, I want get the information to show it in Home Assistant, so just I installed grott as docker in my docker compose, I've all Home Assistant components in the same docker-compose like:

```
version: "3.9"
services:

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    privileged: false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/mosquitto:/mosquitto/config
      - ./data/mosquitto:/mosquitto/data
      - ./log/mosquitto:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      domotica:
        ipv4_address: 172.30.1.220
        aliases:
          - mqtt

  grott:
    container_name: grott
    image: ledidobe/grott
    restart: unless-stopped
    privileged: false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/grott/grott.ini:/app/grott.ini
    ports:
      - "5279:5279"
    networks:
      domotica:
        ipv4_address: 172.30.1.222
        aliases:
          - grott
    environment:
      - TZ=Europe/Rome

networks:
  domotica:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-domotica
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24
```

grott.ini file is:
```
[Generic]
mode = proxy

[Growatt] 

[MQTT]
ip = 172.30.1.220
port = 1883
topic= energy/growatt
auth = True
user = [username]
password = [password]

[PVOutput]

[influx]

[extension] 
```

Than I logged in my Growatt Shinelink/-X Setting Center (IP: 192.168.0.18) and under NetWork Setting I changed:
ResolvDomain -> Off
Server IP -> 192.168.0.100 (Server IP with docker)

But I receive follows errors:
         - Grott connection error
         - peer has disconnected
         - ('192.168.0.18', 1057) has connected
         - Grott connection error
         - peer has disconnected
         - ('192.168.0.18', 1058) has connected
         - Grott connection error
         - peer has disconnected
         - ('192.168.0.18', 1059) has connected
         - Grott connection error
         - peer has disconnected
         - ('192.168.0.18', 1060) has connected
        
The server has lastes Debian with iptables not enable to filter any traffic, docker it's lastes version as the Grott docker image.
