### ISSUE TITLE
Help with timestamps

### ISSUE THREAD

**Issue by EasyBizz** [johanmeijer/grott#308]
Please help, I’m going insane trying to solve this:

this is my shell command for a rpi docker:

docker run -d -p 5279:5279 --restart on-failure -e gnomqtt="True" -e gblockcmd="True" -e gpvoutput="True" -e TZ=Europe/Amsterdam -e gtime="server" -e gtimezone=Europe/Amsterdam -e gpvapikey="{APIKEY}" -e ginvtype="tl3" -e gpvsystemid="{SystemID}" ledidobe/grottrpi

Everything works perfect (pvoutput recieves) but the timestamps keep being GMT (1 hour to early) 
The server time:

docker exec -it {containderID} date

is also GMT, not Europe/Amsterdam

what am I doing wrong?

**Comment by Yogi4301** [comment]
Did you try the same with docker compose? With the shown config I get the correct time


```
version: '3.3'
services:
    grott:
        image: ledidobe/grottrpi:2.7.8
        container_name: growatt
        restart: on-failure
        ports:
            - 5279:5279
        environment:
            - gnomqtt=False
            - gmqttip=192.168.178.69
            - gpvoutput=True
            - gverbose=False
            - gpvtemp=True
            - gtime=server
            - gpvapikey=<MyAPIKey>
            - gpvsystemid=<MySystemID>
            - gblockcmd=True
            - gpvdisv1=True
            - TZ=Europe/Amsterdam
```
