### ISSUE TITLE
Grott will not start after upgrading to the latest version

### ISSUE THREAD

**Issue by thoompje** [johanmeijer/grott#440]
After upgrading the Grott - HA Extension to Grott 2.7.8 i got the following error and the Addon will not start on Home Assistant

Home Assistant 2023.10.1
Supervisor 2023.10.0

**Config Add-on:**

```
data_path: /config/grott
gmode: proxy
grott_mqtt: false
ginvtype: default
ginvtypemap: ""
retain: false
verbose: false
ha_plugin: true
mqtt:
  host: core-mosquitto
  port: 1883
  username: XXXXXX
  password: XXXXXX
gnomqtt: false
gpvoutput: false
```

**Add-on Log**:

```
-----------------------------------------------------------
 Add-on: grott
 The Growatt inverter monitor with current HA plugin integrated
-----------------------------------------------------------
 Add-on version: 044729b
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.10.1
 Home Assistant Supervisor: 2023.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[08:09:15] INFO: Preparing to start...
./script.sh: line 230: GROTT_CONFIG_MQTT_USER: unbound variable
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
