### ISSUE TITLE
Mqtt to home assistant energy dashboard

### ISSUE THREAD

**Issue by wderuijter** [johanmeijer/grott#70]
@johanmeijer small tip regarding https://github.com/johanmeijer/grott/wiki/Home-Assistant-configuration-examples#example-2

If you want to use the data in the energy dashboard they need a "last reset" attribute. So I added this to my configuration file so the total and day value get a last reset date:
```
homeassistant:
  customize_glob:
    sensor.growatt_*_energy*:
      last_reset: '1970-01-01T00:00:00+00:00'
      device_class: energy
      state_class: measurement
```
Perhaps there are better methods but this seems to work so far.

**Comment by johanmeijer** [comment]
Added to the wiki page this one can be closed I think?

**Comment by wderuijter** [comment]
@johanmeijer a minor fix for it to keep working in home assistant. You might want to add it to the wikipage.

```
homeassistant:
  customize_glob:
    sensor.growatt_generated_energy_total:
      state_class: total_increasing
      device_class: energy
      unit_of_measurement: kWh
```
