### ISSUE TITLE
MOD5000TL3-X epvtotal counter data with decreased value results in hass energy dashboard spike

### ISSUE THREAD

**Issue by JasperE84** [johanmeijer/grott#99]
Recently I've seen this happen two or three times on my config:

```
jasper@ubuntu01:~/hass$ egrep -i '(vtotal).+:  [2][1][5].[6-7]' ~/grott.log
                 -  epvtotal             :  215.6
                 -  epvtotal             :  215.6
                 -  epvtotal             :  215.6
                 -  epvtotal             :  215.6
                 -  epvtotal             :  215.6
                 -  epvtotal             :  215.6
                 -  epvtotal             :  215.6
                 -  epvtotal             :  215.7 <---- .1 up
                 -  epvtotal             :  215.6 <---- .1 down, causes reset in HASS and a 215.6 kWh production in energy dashboard
                 -  epvtotal             :  215.6
                 -  epvtotal             :  215.6
```

This is my home assistant server config:

```
  customize_glob:
    sensor.growatt_*_energ*:
      last_reset: '1970-01-01T00:00:00+00:00'
      device_class: energy
      state_class: total_increasing

```

This results in an home assistant spike in energy dashboard:
![image](https://user-images.githubusercontent.com/12022716/154850475-beb4f346-b88f-4399-b06b-5edade436256.png)

Any ideas how to prevent this? 
I changed total_increasing in the hass config to measurement hoping that'll fix it.
